steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT} || exit 0']
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '--cache-from',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        '${_ENVIRONMENT}-fma',
        '--image',
        'gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}',
        '--platform',
        'managed',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
      ]

images:
  - gcr.io/$PROJECT_ID/${_APP_NAME}:${_ENVIRONMENT}
timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
  
  
  
